class EnvironmentSettings:
    def __init__(self):
        self.workspace_dir = r"C:\AIC\ORTrack"
        self.tensorboard_dir = r"C:\AIC\ORTrack\tensorboard"
        self.pretrained_networks = r"C:\AIC\ORTrack\pretrained_networks"
        self.lasot_dir = r"C:\AIC\Data\lasot"
        self.got10k_dir = r"C:\AIC\Data\got10k\train"
        self.got10k_val_dir = r"C:\AIC\Data\got10k\val"
        self.lasot_lmdb_dir = r"C:\AIC\Data\lasot_lmdb"
        self.got10k_lmdb_dir = r"C:\AIC\Data\got10k_lmdb"
        self.trackingnet_dir = r"C:\AIC\Data\trackingnet"
        self.trackingnet_lmdb_dir = r"C:\AIC\Data\trackingnet_lmdb"
        self.coco_dir = r"C:\AIC\Data\coco"
        self.coco_lmdb_dir = r"C:\AIC\Data\coco_lmdb"
        self.lvis_dir = ""
        self.sbd_dir = ""
        self.imagenet_dir = r"C:\AIC\Data\vid"
        self.imagenet_lmdb_dir = r"C:\AIC\Data\vid_lmdb"
        self.imagenetdet_dir = ""
        self.ecssd_dir = ""
        self.hkuis_dir = ""
        self.msra10k_dir = ""
        self.davis_dir = ""
        self.youtubevos_dir = ""
